[build]
  functions = "functions"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  port = 8888

[functions]
  node_bundler = "esbuild"